### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by Walono** [vincenzobaz/VBTALL-ADA2017#1]
- [ ]  Dataframe conflict clean @thomasavon 
- [ ] Dataframe refugee clean @laurierloi 
- [ ]  Dataframe with language, ethnicity, religion @vincenzobaz 
- [ ]  Functions to generate weighted networks from dataframes
- [ ]  Functions to generate maps from dataframes
- [ ]  Functions to generate maps (with edge) from networks
- [ ]  Merge and beautify
- [ ]  Statistics: intensity for conflicts
- [ ]  Statistics: correlations between params over time and distance
